### ISSUE TITLE
Incorporate a Remote handling framework like Red

### ISSUE THREAD

**Issue by max-bacon** [Iron-Stag-Games/Pronghorn#9]
I noticed one of your con's was the inability to create events natively, but I thought a great way to fix this would be through a framework like Red which, in addition to automatically creating events, provides faster speeds than using conventional remotes.

That repo can be found here: https://github.com/Uncontained0/Red

**Comment by hoontee** [comment]
Pronghorn used to have remote batching through a single RemoteEvent which saved on performance. Remote batching was recently removed due to it breaking important net traffic ordering and causing an obscure bug in one of my team's games.
